- hosts: webservers
  gather_facts: no
  vars:
    users:
      - "jaime"
      - "sansa"
      - "robert"
  tasks:
    - name: install git
      ansible.builtin.apt:
        name: git
        state: latest
      become: yes

    - name: add test users
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
      loop: "{{ users }}"
      become: yes

    - name: update .gitconfig
      ansible.builtin.template:
        src: templates/.gitconfig.j2
        dest: "/home/{{item}}/.gitconfig"
      loop: "{{ users }}"
      become: yes

    - name: update authorized_keys
      ansible.builtin.copy:
        src: files/id_rsa.pub
        dest: "/home/{{item}}/.ssh/authorized_keys"
      loop: "{{ users }}"
      become: yes
